services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s       # Check every 10 seconds
      timeout: 5s         # Timeout for each check
      retries: 5          # Retry up to 5 times before marking as unhealthy

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:1234@db:5432/dbname
    depends_on:
      db:
        condition: service_healthy  # Wait until the db service is healthy
    networks:
      - default

volumes:
  db_data:
